{% set name = "repro-zipfile" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/repro_zipfile-{{ version }}.tar.gz
  sha256: 978b384540a9b9b5dff8af5368ebffdd951eb3f4249f2098b6add78f7c826f2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - repro_zipfile
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A tiny, zero-dependency replacement for Python's zipfile.ZipFile for creating reproducible/deterministic ZIP archives.
  home: https://github.com/drivendataorg/repro-zipfile
  dev_url: https://github.com/drivendataorg/repro-zipfile
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jayqi
