{% set name = "repro-zipfile" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/repro_zipfile-{{ version }}.tar.gz
  sha256: 7d24c9d2da4ecde3baeeb8c63b78f4cb5066674d9c3fd7ba72d8d58726c6d013

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - repro_zipfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A tiny, zero-dependency replacement for Python's zipfile.ZipFile for creating reproducible/deterministic ZIP archives.
  home: https://github.com/drivendataorg/repro-zipfile
  dev_url: https://github.com/drivendataorg/repro-zipfile
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jayqi
